x-php: &php
  build:
    context: docker/php
    dockerfile: php.dockerfile
    args:
      ENVIRONMENT: development
  restart: unless-stopped
  working_dir: /srv
  volumes:
    - .:/srv
    - ~/.composer:/home/composer/.cache/composer
    - ~/.composer/auth.json:/config/composer/auth.json
    - ./vendor:/srv/vendor:delegated

services:

  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    command: >-
      --entryPoints.web.address=:80
      --entryPoints.web.http.redirections.entrypoint.to=web-secure
      --entryPoints.web.http.redirections.entrypoint.scheme=https
      --entryPoints.web-secure.address=:443
      --api=true
      --api.dashboard=true
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --providers.file.directory=/srv/configs
      --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/srv
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.services.traefik.loadBalancer.server.port=8080

  php:
    <<: *php
    labels:
      - traefik.enable=true
      - traefik.http.routers.php.entryPoints=web-secure
      - traefik.http.routers.php.rule=Host(`app.docker.localhost`) || Host(`api.docker.localhost`)
      - traefik.http.routers.php.tls=true

  queue:
    <<: *php
    command: php artisan horizon

  scheduler:
    <<: *php
    command: supercronic /srv/docker/php/config/schedule.cron

  mysql:
    image: mysql:8.0-debian
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  mailpit:
    image: axllent/mailpit:v1.12
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.entryPoints=web-secure
      - traefik.http.routers.mailpit.rule=Host(`mailpit.docker.localhost`)
      - traefik.http.routers.mailpit.tls=true
      - traefik.http.services.mailpit.loadBalancer.server.port=8025

volumes:
  redis-data:
  mysql-data:
